site_name: QuantixOne_Documentation
site_url: https://docs.quantixone.com
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.sections
    - search.highlight
    - search.suggest
    - toc.integrate
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - content.action.edit
    - content.action.view
    - announce.dismiss
    - header.autohide
  custom_dir: overrides

plugins:
  - search
  - mike:
      alias_type: symlink

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - def_list
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.smartsymbols
  - pymdownx.betterem

nav:
  - Home: index.md
  - Onboarding: Onboarding.md
  # - Format: Mkdocs-format.md ``commented out check the file for the guide to create mkdocs format``
  - About: about.md